title: Víctor Ramos Menéndez # your name (or website title) here
logo: "/images/FotoVictor.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Videogame Developer  
  <br><br>
  <a href="https://www.linkedin.com/in/v%C3%ADctor-ramos-men%C3%A9ndez-178b39159/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
